/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev`/`next build` on
// first run and should not be edited. It's included here as a placeholder
// since this project has never actually been built in this environment.
